### PR TITLE
Various necessary fixes

### LINKED ISSUE #64: shimcssproperties flag is not set for ShadyCSS in tests
From what I discovered `?wc-shimcssproperties` sets only  `window.WebComponents.flags.shimcssproperties = true` but not `window.ShadyCSS.shimcssproperties = true;

That's why such combination is not being tested in browsers that supports it.

For example, those tests for https://github.com/webcomponents/shadycss/issues/47 were passing in Chrome even though they shouldn't.

### PR DESCRIPTION
**Pull request by azakus**
Fixes webcomponents/webcomponentsjs#739
Fixes #64

### CODE REVIEW

File: tests/test-flags.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
+/**
+ * @license
+ * Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
```
Comment (notwaldorf) [inline tests/test-flags.js]: 2017?
