### PR TITLE
Fix async loading

### LINKED ISSUE #94: Consider lazy-loading support for CustomStyleInterface and ApplyShim
Right now, the first call to `ShadyCSS.prepareTemplate`,  `styleElement`, `styleDocument` or `styleSubtree` will lock-in the state of CustomStyleInterface and ApplyShim. This avoids the complexity of recalculating all styles if CustomStyleInterface or ApplyShim load later.

However, this is in conflict with lazy-loading strategies like the [PRPL pattern](https://developers.google.com/web/fundamentals/performance/prpl-pattern/).

Steps needed to support lazy-loading
- Redo mixin detection in `prepareTemplate` to be lazy
- Make the `ensure` dependency functions in each library reset
- Maybe an API when lazy-loaded that handles full-document refresh

### LINKED ISSUE #95: Loading ApplyShim and CustomStyleInterface asynchronously is problematic
The `ApplyShim` needs to register callbacks with `CustomStyleInterface` so that `CustomStyleInterface` supports `@apply`. This registration occurs via an `ensure` method that is called whenever the user attempts to use `ApplyShim` and when dependencies in document are loaded (a RAF after readyState interactive). Unfortunately, this document state check is not correct when `ApplyShim` is loaded after initial dependencies have loaded. This means `ApplyShim` can fail to register with `CustomStyleInterface`. Since `ensure` only tries to do the registration once, if it fails, the system is broken.

That state check is probably hard to fix, so instead we should probably just have `ensure` be able to check if `CustomStyleInterface` has come into existence and patch if it has.

### PR DESCRIPTION
**Pull request by azakus**
Fixes #94
Fixes #95

### CODE REVIEW

File: entrypoints/apply-shim.js [hunk 1]
```diff
@@ -26,14 +26,14 @@ class ApplyShimInterface {
   constructor() {
     /** @type {?CustomStyleInterfaceInterface} */
     this.customStyleInterface = null;
-    this.booted = false;
+    this.elementsHaveApplied = false;
```
Comment (sorvell) [inline entrypoints/apply-shim.js]: What is this for?

File: src/custom-style-interface.js [hunk 2]
```diff
@@ -140,14 +140,8 @@ Object.defineProperties(CustomStyleInterface.prototype, {
...
     set(fn) {
-      let needsEnqueue = false;
-      if (!validateFn) {
-        needsEnqueue = true;
-      }
       validateFn = fn;
-      if (needsEnqueue) {
-        this.enqueueDocumentValidation();
-      }
+      this.enqueueDocumentValidation();
```
Comment (sorvell) [inline src/custom-style-interface.js]: Why is this change important?
