### PR TITLE
Do not replace "inherit" and "initial" in fallbacks

### LINKED ISSUE #91: `inherit` within `@apply` definitions gets overriden by User-Agent styles
### Description
`inherit` within `@apply` definitions gets overriden by User-Agent styles, which didn't happen in Polymer 1.x with full WebComponents v0 polyfill (and without it in Chromium), but now happens in Polymer 2.0 and WebCmponents v1 lite.

#### Live Demo
https://jsbin.com/guwinowudo/edit?html,output

#### Steps to Reproduce
1. Define `@apply` definition with `font-family` set to `inherit`
2. Speficy non-default `font-family` for `body`
3. Use `@apply` rule in element in `::slotted(button)`

#### Expected Results
`inherit` effectively applies `body`'s `font-family`

#### Actual Results
User-Agent's `font-family` has higher specificity, actual `font-family` is shown as `apply-shim-inherit` in Dev Tools in both tested browsers.

### Browsers Affected
Only tested in these:
- [x] Chromium nightly
- [x] Firefox

### Versions
Polymer: 2.0-preview

### PR DESCRIPTION
**Pull request by azakus**
Fixes #91

### CODE REVIEW

File: src/apply-shim.js [hunk 1]
```diff
@@ -386,9 +386,10 @@ class ApplyShim {
    * "parse" a mixin definition into a map of properties and values
    * cssTextToMap('border: 2px solid black') -> ('border', '2px solid black')
    * @param {string} text
+   * @param {boolean=} replaceInitialOrInherit
    * @return {!Object<string, string>}
    */
-  _cssTextToMap(text) {
+  _cssTextToMap(text, replaceInitialOrInherit = true) {
```
Comment (sorvell) [inline src/apply-shim.js]: Suggest making this argument default to `false`. Just easier to understand.
